CC = gcc
FLAGS = -Wall -std=c99 -pedantic


all: P11 P12  P21 P22 P23

clean:
	rm -f  *.exe *.out  P11 P12  P21 P22 P23

# Problem 1

P11: P1.h P11.c
	$(CC) P11.c $(FLAGS) -o P11

P12: P1.h P12.c
	$(CC) P12.c $(FLAGS) -o P12


# Problem 2

P21: P2.h P21.c
	$(CC) P21.c $(FLAGS) -o P21

P22: P2.h P22.c
	$(CC) P22.c $(FLAGS) -o P22

P23: P2.h P23.c
	$(CC) P23.c $(FLAGS) -o P23

